server:
  port: ${PORT:8080}

database:
  enabled: true
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:mysecretpassword}
  name: ${DB_NAME:foodie}

queue:
  enabled: true
  url: nats://localhost:4222
  name: default
  prefix: events
  maxAge: 24h
