// Code generated by interfacer, DO NOT EDIT.
package server

import (
	"context"
	"net/http"
)

// Server defines the public interface for server.
type Server interface {
	// AddHandler registers a new handler for the specified path.
	AddHandler(path string, handler http.HandlerFunc)
	// AddMiddleware adds a middleware function to the server.
	AddMiddleware(middleware MiddlewareFunc)
	// Starts a running server by the given address.
	// Stops the server when it receives ctx.Done()
	Start(ctx context.Context, addr string) error
}
