# Use postgres/example user/password credentials
services:

  # Database
  db:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foodie
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 3
  
  # Message queue
  nats:
    image: nats:2.10.24-alpine
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--jetstream"
      - "--http_port"
      - "8222"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8222 || exit 1"]
      start_period: 3s
      retries: 3
      timeout: 3s
      interval: 5s

  # Cache
  cache:
    image: valkey/valkey:7.2.5-bookworm
    ports:
      - "6379:6379"
