// Code generated by interfacer, DO NOT EDIT.
package queue

import "time"

// Queue defines the public interface for pubsubClient.
type Queue interface {
	// Runs a consumer by given configuration and callback function
	// OBS: This function is blocking, so make sure to run it in a goroutine if
	// you want to run other code in parallel.
	// Returns an error if the consumer could not be created or updated.
	Consume(config ConsumerConfig) error
	// Publishes a message to the specified topic.
	// The function accepts a variadic parameter for timeout duration, defaulting to 5 seconds if not provided.
	Publish(topic string, message []byte, timeout ...time.Duration) error
}
