name: Continuous Integration

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  # Runs the build process to ensure that the code compiles and is ready for deployment.
  test:
    name: Run tests.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24.5"
          cache-dependency-path: go.sum
      - name: Run tests
        run: |
          docker compose -f docker-compose.ci.yml up -d --wait
          go test -v -coverpkg=./... -coverprofile cover.out ./...
          docker compose -f docker-compose.ci.yml down
  # Runs golangci-lint to check for code quality issues.
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "^1.24.5"
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout=10m
          version: v2.1.0
